### ISSUE TITLE
feat(quantity-picker): Make extensible

### ISSUE THREAD

**Issue by lauthieb** [Decathlon/vitamin-compose#102]
**Is your feature request related to a problem? Please describe.**

Actually, QuantityPicker has a fixed size.

**Describe the solution you'd like**

But depending on the content we need to make it extensible.

Related issue: https://github.com/Decathlon/vitamin-design/issues/162

**Comment by ManonPolle** [comment]
Closed by https://github.com/Decathlon/vitamin-compose/pull/70
