### ISSUE TITLE
bug: Difference between Design and Dev Dialog

### ISSUE THREAD

**Issue by felixbusadkt** [Decathlon/vitamin-compose#115]
**Describe the bug**
Dialog is different from the design propose by Vitamin : 
* There is no border radius
* Actions or not side to side
* Padding between action and bottom border is too wide

**Steps to reproduce**

**Expected behavior**
The dialog should be the same as that visible on Vitamin

**Screenshots**
https://www.figma.com/file/YLNocCTjGjcw6SiSRGoSu3/%F0%9F%91%8C-CISB-1567%3A-Design-Validation---Dialog?node-id=3328%3A7900

**Device (please complete the following information):**
- Model: moto g(9) play
- OS: Android
- Version 10

**Comment by ManonPolle** [comment]
Figma has been updated with radius & elevation for modals, so we need to update Modal Component on vitamin-compose. 

@Decathlon/design-system-core-team-design decathlon.design need to be updated as weel
