### ISSUE TITLE
VitaminSnackbars don't disappear automatically after a set of time

### ISSUE THREAD

**Issue by tlevavasseur-decathlon** [Decathlon/vitamin-compose#136]
**Describe the bug**

`VitaminSnackbars` don't _disappear automatically after a set of time_.

> **Multiple Snackbar**
> Only one snackbar may be displayed at a time. If multiple snackbars need to appear, the new one replaced the previous one. The snackbar can disappear automatically after a set of time or can be dismissed by the user. 

https://www.decathlon.design/726f8c765/p/798580-snackbar/b/81bb90

**Expected behavior**

An option to enable auto disappearance (and eventually a customisable delay) or at least a sample of how to do it.

**Comment by ManonPolle** [comment]
Vitamin provide a visual for the Snackbar. It is when you implement it and display it that you can set a duration, with a custom `SnackbarHost`

```
SnackbarHost(snackbarHostState) { snackbarData-> 
             Box(modifier = Modifier.padding(4.dp)) {
                VitaminSnackbars.Primary(text = snackbarData.message)
            }
        }
```

and then 

```
coroutineScope.launch {
                        snackbarHostState.showSnackbar(
                            message = "Description of the snackbar",
                            actionLabel = null,
                            duration = SnackbarDuration.Short,
                        )
                    }
```

I close this issue as it is not Vitamin responsability but feel free to reach out to me if needed
