### ISSUE TITLE
bug(modals): modal fill the screen width on specific device

### ISSUE THREAD

**Issue by corentin-stamper** [Decathlon/vitamin-compose#138]
**Describe the bug**

Modal fill the screen width on Samsung Galaxy A13

**To Reproduce**
1. Go to the sample app
2. Open `Modals`
3. Display a modal

**Screenshots**
![image](https://user-images.githubusercontent.com/46709142/233014601-650472ca-280b-428a-b89a-505df6dba3a7.png)

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy A13
- Android version: 13
- One UI Core version: 5.0

**Comment by ManonPolle** [comment]
Thanks for creating this issue ! We will analyse this

**Comment by corentin-stamper** [comment]
This issue is specific to this device and we are unable to resolve it at this time.
