### ISSUE TITLE
RadioButton not centered

### ISSUE THREAD

**Issue by adrienmu** [Decathlon/vitamin-compose#143]
**Describe the bug**
The component VitaminRadioButtons.Primary(selected = true, onClick = null) is not centered

**Screenshots**
![image](https://user-images.githubusercontent.com/58910280/236135500-79c8ea22-eaa0-485b-a759-84a04494211e.png)

**Comment by ManonPolle** [comment]
Thanks a lot @adrienmu for creating this issue, we will analyse this as soon as possible :)
