### ISSUE TITLE
Text inputs are not vitamin compliant

### ISSUE THREAD

**Issue by adrienbusin** [Decathlon/vitamin-compose#15]
**Describe the bug**

The text input filled is not vitamin compliant, the row is too long. 

**To Reproduce**

<img width="343" alt="Capture d’écran 2022-06-02 à 14 13 37" src="https://user-images.githubusercontent.com/16080757/171626683-cfe07b77-13bc-4f7d-b93f-c557bbd8865b.png">

**Expected behavior**

https://www.decathlon.design/726f8c765/p/31121d-text-input/b/601da7
No margin is required.
![image](https://user-images.githubusercontent.com/16080757/171626179-3ab493f7-7848-49c8-a3f9-523f75975306.png)

**Screenshots**

**Smartphone (please complete the following information):**

- Device: [e.g. One Plus]
- OS: [e.g. Lollipop]
- Version [e.g. 21]

**Comment by GerardPaligot** [comment]
I think it is more a bug in the design specification. Vitamin Android should follow Material guidelines which add this margin.

Note that for information, with Compose, we can remove this margin. You can find this property in Compose source code:

```kotlin
internal val HorizontalIconPadding = 12.dp
```

Which is applied automatically before the label.

**Comment by N0t-Simon** [comment]
Jira created, we'll be back asap with answers & / or Fix.

**Comment by lauthieb** [comment]
@GerardPaligot @adrienbusin @felixbusadkt it's done for design part now, you can do it :)
Thanks for your patience!

**Comment by GerardPaligot** [comment]
So there is no more issue here from our side because it is the standard way to display a filled text input.
Thanks.
