### ISSUE TITLE
bug(ratings): Whole number ratings displays as half ratings

### ISSUE THREAD

**Issue by Gregesteban** [Decathlon/vitamin-compose#151]
**Describe the bug**

When providing whole number rating to a VitaminRatings.ReadOnly composable, it is displayed with a half more note that it should.

According to a bit of debugging, a missing case of handling .0 decimals is located [here](https://github.com/Decathlon/vitamin-compose/blob/3221854c66013c2a51bba5cc8aecdeb31c2a8244/ratings/src/main/java/com/decathlon/vitamin/compose/ratings/Icon.kt#L23)

**To Reproduce**

**Expected behavior**

There should be no half stars displayed.

**Screenshots**

Here the exact note is 3.0
<img width="183" alt="image" src="https://github.com/Decathlon/vitamin-compose/assets/128040366/3f289c1c-a980-4606-8935-3cd9f21b79ad">

**Smartphone (please complete the following information):**

- Device: Samsung Galaxy S8
- OS: Pie
- Version 28

**Comment by ManonPolle** [comment]
Thanks a lot for spotting and creating this issue. We will look at it as soon as possible.
Don't hesitate to contribute if you'd like.
