### ISSUE TITLE
bug(ratings): Ratings around half value are wrongly choosen

### ISSUE THREAD

**Issue by olivierperez** [Decathlon/vitamin-compose#175]
**Describe the bug**

Reading [Design System's Rating doc](https://www.decathlon.design/726f8c765/p/19ec87-rating/b/63b428) it seemed that the number of stars shown in `VitaminRatings` isn't correct.

For instance:
- the value 3.2 is closer to 3.0 than 3.5, so it should show ★★★✩✩ but it is showing ★★★\[half-star]✩
- the value 3.5 is strictly equal to 3.5, so it should show ★★★\[half-star]✩ but it is showing ★★★★✩
- the value 3.6 is closer to 3.5 than 4.0, so it should show ★★★\[half-star]✩ but it is showing ★★★★✩

I double checked it by playing with the [showcase](https://www.decathlon.design/726f8c765/p/19ec87-rating/t/11512d).

**To Reproduce**
Show a Ratings with the values given as example above.

**Screenshots**
Actual ratings of 3.0, 3.1, ..., 3.9, 4.0
![image](https://github.com/Decathlon/vitamin-compose/assets/883959/72d8768b-833e-4341-8670-0318c43a8953)
Excpected ratings of 3.0, 3.1, ..., 3.9, 4.0
![image](https://github.com/Decathlon/vitamin-compose/assets/883959/66b048ad-c9a3-4bcd-b82e-3ce8273d18d6)

**Smartphone (please complete the following information):**

- Device: One Plus 6
- OS: Red Velvet Cake
- Version: 11

**Comment by ManonPolle** [comment]
Thanks a lot for this complete issue and pull request ! I'll check as quick as possible
