### ISSUE TITLE
feat (text-inputs): better space allocation between helpertext and counter

### ISSUE THREAD

**Issue by dimitriz09** [Decathlon/vitamin-compose#177]
**Describe the bug**
On a textinput, when using both helpertext and counter, the space allocation is 50/50. Preventing us to display useful help. 

![Screenshot from 2023-10-04 09-56-53](https://github.com/Decathlon/vitamin-compose/assets/109512997/bbca4d55-c916-4c2b-9169-ccd3c538d730)

As you can see, with an invalid postal code, we'd like to display an example, unfortunately we are running out of space and the text ellipsizes. Yet, the counter next to it has plenty of space. 
Maybe allow the helper to take all necessary space.

**Comment by ManonPolle** [comment]
Thanks @dimitriz09 for this issue, you're right we could optimize the space. 
Contributors or I will check as soon as we can
