### ISSUE TITLE
feat(textinputs): allow us handle cursor position in text inputs

### ISSUE THREAD

**Issue by dimitriz09** [Decathlon/vitamin-compose#180]
**Context:** 
I have an edit field for phone number, which auto formats number as it is typed. 
When the auto formats adds a space between digits block (like in french phone numbers) or a dash (like in US phone numbers), the actual value length is incrase by 2 (the added separator, and the actual digit typed)  but unfortunately, the cursor only only registers one more char, i would need to force it to the end, but for that, i need the material impl using TextFieldValue instead of basic String

I can provide a video via slack, i have it ready i just can't upload it here.

I would like to be able to use
```
var textState by remember { mutableStateOf("Some text") }
VitaminTextInputs.Outlined(
    ...
    value = TextFieldValue(textState, selection = TextRange(textState.length)),
    ...
)
```

**Comment by ManonPolle** [comment]
Thanks a lot @dimitriz09 for spotting this. We'll analyse when we can add this case. fill free to submit a contribution if you want it handled quicker :)
