### ISSUE TITLE
WonderTheme doesn t recompose when darkTheme change

### ISSUE THREAD

**Issue by dgaillard2** [Decathlon/vitamin-compose#185]
**Describe the bug**
When I try to dynamically switch between light and dark themes using WonderTheme in my app, the theme's visual elements don't update correctly. The text changes as expected, but the theme colors (containers and text) do not recompose accordingly. This works perfectly with AppTheme, but not with WonderTheme.

**To Reproduce**

Implement a compose app using WonderTheme and a variable isDarkTheme (as a mutableStateOf to produce recomposition).
Update the value of isDarkTheme via an event (e.g., by clicking a button).
Notice that while the text changes correctly, the theme colors do not update.

A snippet for reproduce : 
```
var isDarkTheme by remember { mutableStateOf(true) }
WonderTheme(darkTheme = isDarkTheme) {
    Column(modifier = Modifier.background(VitaminPlay.colors.containerNeutral)) {
        Text(
            text = "Current theme: ${if (isDarkTheme) "Dark" else "Light"}",
            color = VitaminPlay.colors.contentNeutral,  
            modifier = Modifier
                .padding(16.dp)
                .background(VitaminPlay.colors.containerNeutral)  
        )
        Text(
            text = "DARK",
            Modifier
                .background(Color.Red)
                .clickable { isDarkTheme = true })
        Text(
            text = "LIGHT",
            Modifier
                .background(Color.Red)
                .clickable { isDarkTheme = false })
    }
}
```

**Expected behavior**
WonderTheme should switch DARK <-> LIGHT when switching between dark and light themes

**Comment by ManonPolle** [comment]
Thanks @dgaillard2 for your issue, We'll have a look a this soon. I just transfer this issue to the right repository and close this one :)
