### ISSUE TITLE
feat: add testTag for automated testing

### ISSUE THREAD

**Issue by damien-toulouse** [Decathlon/vitamin-compose#30]
**Is your feature request related to a problem? Please describe.**
When writing automated test on compose screen using component like OutlinedDropdown the lack of testTag modifier on subComponent make those screen hard to test

**Describe the solution you'd like**
Add testTag on component with userInteraction, for example to trigger the click on the trailing Icon of the anchored Outlined of a OutlinedDropdown

**Comment by GerardPaligot** [comment]
Can you be more precise about "subComponent" inside the `OutlinedDropdown`? Options declared in the outlined dropdown is declared by you and so, you can attach your own test tag who can fit your needs for the test strategy of your product.

**Comment by damien-toulouse** [comment]
Hello @GerardPaligot 
Currently if we set a testTag as a `Modifier` in the `OutlinedDropdown` parameters it add it to the `Dropdown` component.
Problem is if you need to access the anchored `Outlined` or even the `Icon` of that `Outlined` for exemple to open or close the `DropDown`

**Comment by GerardPaligot** [comment]
Ok got it. You don't speak about options of a dropdown but atomic elements inside the text field. Interesting.

We need to think of a approach who can let you give us these test tags because we can't apply the test tag for all text inputs in a screen.

**Comment by ManonPolle** [comment]
Closed by https://github.com/Decathlon/vitamin-compose/pull/169
