### ISSUE TITLE
feat: add Card Component

### ISSUE THREAD

**Issue by GerardPaligot** [Decathlon/vitamin-compose#5]
**Decathlon.design link**

https://www.decathlon.design/726f8c765/p/88fc2b-card-beta

> Design update: We want only a **card container** with its specifications but NO content templates. 

**Material.io link**

https://material.io/components/cards

**Comment by ManonPolle** [comment]
design update : We want only a card container with its specifications but NO content templates.

**Comment by lauthieb** [comment]
For your information: https://github.com/Decathlon/vitamin-design/issues/129
