### ISSUE TITLE
feat: add Fab Component

### ISSUE THREAD

**Issue by FDELAHA24** [Decathlon/vitamin-compose#50]
**Decathlon.design link**

https://www.decathlon.design/726f8c765/p/8008f8-button/b/58097e/t/47f29a

**Material.io link**

https://m3.material.io/components/floating-action-button/overview
https://m3.material.io/components/extended-fab/overview

**Additional context**

**Comment by ManonPolle** [comment]
Linked Design request:  https://github.com/Decathlon/vitamin-design/issues/128
