### ISSUE TITLE
bug: Add vertical padding for Snackbar component

### ISSUE THREAD

**Issue by ManonPolle** [Decathlon/vitamin-compose#55]
**Describe the bug**
See https://github.com/Decathlon/vitamin-design/issues/90

Concerning
<img width="355" alt="image" src="https://user-images.githubusercontent.com/46710837/206417790-3973f397-f7ee-42d9-a28d-1a3c03d1f843.png">

**Comment by logickoder** [comment]
Can I take this issue?

**Comment by ManonPolle** [comment]
Hello

If you still need this fix, yes you can take the issue and see our process
& guidelines into our CONTRIBUTING.md
<https://github.com/Decathlon/vitamin-compose/blob/main/CONTRIBUTING.md>,
assign it to yourself & change issue status to Dev In Progress (
https://github.com/orgs/Decathlon/projects/3/views/14)
Someone will check your Pull Request when created.

Don't hesitate if you have any questions

Manon,
Tech lead Android
Vitamin - Decathlon Design System

**Comment by GerardPaligot** [comment]
In Compose, there are hardcoded values for the padding of a Snackbar:

```kotlin
private val HorizontalSpacing = 16.dp
private val HorizontalSpacingButtonSide = 8.dp
private val SeparateButtonExtraY = 2.dp
private val SnackbarVerticalPadding = 6.dp
```

* `HorizontalSpacing` is used for the padding at the beginning before the text and at the end.
* `HorizontalSpacingButtonSide` is used for the padding between the text and the button if it exists.
* `SeparateButtonExtraY` is used as bottom padding for the button if the snackbar have new lines.
* `SnackbarVerticalPadding` is used as top and bottom paddings for the button if the snackbar is on one line.

These paddings are used in internal of the Snackbar and can't be customized.
