### ISSUE TITLE
The ripple effect does not match the design 

### ISSUE THREAD

**Issue by ravenfeld** [Decathlon/vitamin-compose#56]
**Describe the bug**
I have the impression that ripples effect are not good since beta 2 before I was on alpha I did not test your develop branch and maybe it is already fixed.

https://user-images.githubusercontent.com/3765114/206702262-514f5138-335a-49fd-a374-25a56b743360.mp4

**Comment by GerardPaligot** [comment]
I just checked base colors and mapping from base colors and semantics colors and everything seems ok.

Can you tell us what is the configuration of your device or emulator? Device name and Android version. For older versions, there is an hack in the ripple effect which are used by Vitamin but by Compose too:

```kotlin
/**
 * On API 21-27 the ripple animation is split into two sections - an overlay and an
 * animation on top. Due to this split, we need to divide by 2 the original alpha.
 */
private fun getAlpha(alpha: Float = 1f): Float =
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.P) alpha / 2f else alpha
```

Complete code available here from Material Compose artifact with `calculateRippleColor` function: https://androidx.tech/artifacts/compose.material/material-ripple/1.1.1-source/androidx/compose/material/ripple/RippleHostView.android.kt.html

If you are using an Android version under 27, you can have small variations on the alpha of the ripple color.

**Comment by GerardPaligot** [comment]
We made some tests on different devices with different Android versions but with the same code for the ripple effect and the result isn't the same. Each Android version (and even more with API 33 which rework the ripple effect) have its own UI for the same code.

The design team need to take a decision about this fact but I think we'll keep a difference between the implementation and the design for platform OS reasons. We need to document this.

**Comment by ravenfeld** [comment]
This is a pixel 4a in 31 but the same problem on a one plus 7 in 29

**Comment by FDELAHA24** [comment]
@Decathlon/design-system-core-team-design

**Comment by lauthieb** [comment]
@Decathlon/design-system-core-team-design will align & apply native standards for ripple on Figma Android UI Kit file.

**Comment by SimonLeclercq** [comment]
@ManonPolle will generate all the usecase in the `vitamin-sample` after what color + Figma styles will be add to "native color" into `vitamin core theme`

**Comment by SimonLeclercq** [comment]
Discussed with @ManonPolle, Design library will be an XLM representation of Vitamin, and Compose will be entrusted to material automation
