### ISSUE TITLE
feat: Make Fab full width possible 

### ISSUE THREAD

**Issue by ManonPolle** [Decathlon/vitamin-compose#69]
**Describe the solution you'd like**

Make fab full width possible & add it to the sample. 
Design request : https://github.com/Decathlon/vitamin-design/issues/128

**Additional context**

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/46710837/211763588-d10f7ea1-76e8-4dc2-b824-82c369d2460b.png">

**Comment by FDELAHA24** [comment]
To be added in the fab button PR : https://github.com/Decathlon/vitamin-compose/pull/60

**Comment by ManonPolle** [comment]
Closed by https://github.com/Decathlon/vitamin-compose/issues/50
